# Required Metadata
sonar.organization=matthiasliszt
sonar.projectKey=MatthiasLiszt_GitHub-CI-CD-Integration-Demo

# Where the code is (usually the current folder)
sonar.sources=.

# Tell Sonar where the Selenium test results are
# This matches the --junitxml=result.xml from our pytest command
sonar.python.xunit.reportPath=result.xml

# Encoding
sonar.sourceEncoding=UTF-8
